package problem0002;

/**
 * Even Fibonacci numbers Problem 2
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
 * the sum of the even-valued terms.
 */
class SumOfEvenFibonacciNumbers {

  int compute(final int rightBoundary) {
    assert rightBoundary >= 0;

    int result = 0;

    int lastNumber = 1;
    int penultimateNumber = 1;
    while (true) {
      final int nextNumber = lastNumber + penultimateNumber;
      penultimateNumber = lastNumber;
      lastNumber = nextNumber;

      if (nextNumber > rightBoundary) {
        break;
      }

      if (nextNumber % 2 == 0) {
        result += nextNumber;
      }
    }

    assert result >= 0;
    return result;
  }
}
